version: '3.8'

services:
  dehashchat:
    build: .
    container_name: dehashchat
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEHASHED_API_KEY=${DEHASHED_API_KEY}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
    volumes:
      - .:/app
    stdin_open: true # docker run -i
    tty: true # docker run -t
